from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

import joblib
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

ARTIFACTS_DIR = PROJECT_ROOT / "data" / "artifacts"

TFIDF_PATH = ARTIFACTS_DIR / "tfidf_vectorizer.pkl"
MATRIX_PATH = ARTIFACTS_DIR / "occupation_matrix.pkl"
METADATA_PATH = ARTIFACTS_DIR / "occupation_metadata.json"


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# RIASEC constants
# ---------------------------------------------------------------------------

RIASEC_TYPES = (
    "Realistic",
    "Investigative",
    "Artistic",
    "Social",
    "Enterprising",
    "Conventional",
)


# ---------------------------------------------------------------------------
# Artifact loading
# ---------------------------------------------------------------------------

def _check_artifacts() -> None:
    """
    Verify that all artifacts generated by train.py exist.
    """
    required_files = (
        TFIDF_PATH,
        MATRIX_PATH,
        METADATA_PATH,
    )

    missing = [
        str(path)
        for path in required_files
        if not path.exists()
    ]

    if missing:
        raise FileNotFoundError(
            "Required ML artifacts are missing:\n"
            + "\n".join(missing)
            + "\n\nRun preprocessing and training first."
        )


def _load_artifacts():
    """
    Load the trained ML artifacts.

    This function is called once when the module is imported.
    """
    _check_artifacts()

    logger.info("Loading ML artifacts...")

    vectorizer = joblib.load(TFIDF_PATH)

    occupation_matrix = joblib.load(MATRIX_PATH)

    import json

    with open(
        METADATA_PATH,
        "r",
        encoding="utf-8",
    ) as file:
        metadata = json.load(file)

    occupation_order = metadata.get(
        "occupation_order",
        [],
    )

    occupations = metadata.get(
        "occupations",
        {},
    )

    if not occupation_order:
        raise ValueError(
            "occupation_metadata.json contains no occupation order."
        )

    if not occupations:
        raise ValueError(
            "occupation_metadata.json contains no occupations."
        )

    if occupation_matrix.shape[0] != len(occupation_order):
        raise ValueError(
            "Occupation matrix row count does not match "
            "occupation metadata."
        )

    logger.info(
        "Loaded %d occupations",
        len(occupation_order),
    )

    logger.info(
        "TF-IDF vocabulary size: %d",
        len(vectorizer.vocabulary_),
    )

    logger.info(
        "Occupation matrix shape: %s",
        occupation_matrix.shape,
    )

    return (
        vectorizer,
        occupation_matrix,
        metadata,
    )


# ---------------------------------------------------------------------------
# Load once
# ---------------------------------------------------------------------------

vectorizer, occupation_matrix, metadata = _load_artifacts()

occupation_order: List[str] = metadata["occupation_order"]

occupations: Dict[str, Dict[str, Any]] = metadata["occupations"]


# ---------------------------------------------------------------------------
# Text normalization
# ---------------------------------------------------------------------------

def normalize_text(value: Any) -> str:
    """
    Normalize arbitrary input into clean text.
    """
    if value is None:
        return ""

    return " ".join(
        str(value).strip().split()
    )


def normalize_skills(
    user_skills: Sequence[str],
) -> List[str]:
    """
    Clean and deduplicate user-provided skills.
    """
    result: List[str] = []
    seen = set()

    for skill in user_skills:

        skill = normalize_text(skill)

        if not skill:
            continue

        key = skill.lower()

        if key in seen:
            continue

        seen.add(key)
        result.append(skill)

    return result


# ---------------------------------------------------------------------------
# Occupation skill extraction
# ---------------------------------------------------------------------------

def _extract_names(
    items: Any,
) -> List[str]:
    """
    Extract the 'name' field from an occupation metadata list.
    """
    if not isinstance(items, list):
        return []

    result = []

    for item in items:

        if isinstance(item, dict):

            name = normalize_text(
                item.get("name")
            )

            if name:
                result.append(name)

        elif isinstance(item, str):

            item = normalize_text(item)

            if item:
                result.append(item)

    return result


def _occupation_skill_names(
    occupation: Dict[str, Any],
) -> List[str]:
    """
    Collect the textual skill/knowledge/ability/tool terms associated
    with an occupation.

    These fields originate from the processed O*NET datasets.
    """
    fields = (
        "knowledge",
        "abilities",
        "transferable_skills",
        "essential_skills",
        "software_skills",
        "specific_interests",
    )

    names: List[str] = []

    for field in fields:
        names.extend(
            _extract_names(
                occupation.get(field, [])
            )
        )

    # Include hot technologies and in-demand software.
    names.extend(
        normalize_text(value)
        for value in occupation.get(
            "hot_technologies",
            [],
        )
    )

    names.extend(
        normalize_text(value)
        for value in occupation.get(
            "in_demand_software",
            [],
        )
    )

    return _unique_case_insensitive(names)


def _unique_case_insensitive(
    values: Sequence[str],
) -> List[str]:
    """
    Deduplicate strings while preserving order.
    """
    result = []
    seen = set()

    for value in values:

        value = normalize_text(value)

        if not value:
            continue

        key = value.lower()

        if key in seen:
            continue

        seen.add(key)
        result.append(value)

    return result


# ---------------------------------------------------------------------------
# Matched and missing skills
# ---------------------------------------------------------------------------

def _skill_matches(
    user_skills: Sequence[str],
    occupation_skills: Sequence[str],
) -> tuple[List[str], List[str]]:
    """
    Determine which user skills are represented by the occupation
    profile and which are not.

    Matching is case-insensitive and supports simple substring
    matching.

    Example:
        User: "Python"
        Occupation: "Python Programming"

    will be treated as a match.
    """
    normalized_occupation = [
        skill.lower()
        for skill in occupation_skills
    ]

    matched: List[str] = []
    missing: List[str] = []

    for user_skill in user_skills:

        user_skill_lower = user_skill.lower().strip()

        if not user_skill_lower:
            continue

        is_match = False

        for occupation_skill in normalized_occupation:

            if (
                user_skill_lower == occupation_skill
                or user_skill_lower in occupation_skill
                or occupation_skill in user_skill_lower
            ):
                is_match = True
                break

        if is_match:
            matched.append(user_skill)
        else:
            missing.append(user_skill)

    return matched, missing


# ---------------------------------------------------------------------------
# RIASEC utilities
# ---------------------------------------------------------------------------

def _normalize_riasec_profile(
    profile: Optional[Dict[str, Any]],
) -> Dict[str, float]:
    """
    Convert a RIASEC profile into a clean numeric dictionary.
    """
    result = {
        interest_type: 0.0
        for interest_type in RIASEC_TYPES
    }

    if not isinstance(profile, dict):
        return result

    for interest_type in RIASEC_TYPES:

        value = profile.get(
            interest_type
        )

        try:
            if value is not None:
                result[interest_type] = float(value)

        except (TypeError, ValueError):
            result[interest_type] = 0.0

    return result


def _riasec_similarity(
    user_profile: Optional[Dict[str, float]],
    occupation_profile: Dict[str, Any],
) -> float:
    """
    Calculate cosine similarity between the user's RIASEC profile
    and the occupation's O*NET RIASEC profile.

    Returns a value between 0 and 1.
    """
    if not user_profile:
        return 0.0

    occupation_riasec = _normalize_riasec_profile(
        occupation_profile.get(
            "riasec",
            {},
        )
    )

    user_riasec = _normalize_riasec_profile(
        user_profile
    )

    user_vector = np.array(
        [
            user_riasec[item]
            for item in RIASEC_TYPES
        ],
        dtype=float,
    ).reshape(1, -1)

    occupation_vector = np.array(
        [
            occupation_riasec[item]
            for item in RIASEC_TYPES
        ],
        dtype=float,
    ).reshape(1, -1)

    user_norm = np.linalg.norm(
        user_vector
    )

    occupation_norm = np.linalg.norm(
        occupation_vector
    )

    if user_norm == 0 or occupation_norm == 0:
        return 0.0

    similarity = cosine_similarity(
        user_vector,
        occupation_vector,
    )[0][0]

    return float(
        np.clip(similarity, 0.0, 1.0)
    )


# ---------------------------------------------------------------------------
# Industry filtering
# ---------------------------------------------------------------------------

def _matches_industry(
    occupation: Dict[str, Any],
    preferred_industry: Optional[str],
) -> bool:
    """
    Perform a lightweight text-based industry filter.

    The O*NET occupation dataset does not provide a generic
    'industry' column in the processed profile, so the filter
    searches the occupation title and description.

    If no industry is supplied, every occupation is eligible.
    """
    if not preferred_industry:
        return True

    preferred_industry = normalize_text(
        preferred_industry
    ).lower()

    if not preferred_industry:
        return True

    searchable = " ".join(
        [
            normalize_text(
                occupation.get("title", "")
            ),
            normalize_text(
                occupation.get("description", "")
            ),
        ]
    ).lower()

    return preferred_industry in searchable


# ---------------------------------------------------------------------------
# Search text creation
# ---------------------------------------------------------------------------

def _build_user_search_text(
    user_skills: Sequence[str],
) -> str:
    """
    Convert the user's skills into a TF-IDF query document.
    """
    return " ".join(
        normalize_skills(user_skills)
    )


# ---------------------------------------------------------------------------
# Score calculation
# ---------------------------------------------------------------------------

def _calculate_skill_coverage(
    matched_skills: Sequence[str],
    user_skills: Sequence[str],
) -> float:
    """
    Calculate the proportion of user skills matched by the occupation.
    """
    if not user_skills:
        return 0.0

    return len(matched_skills) / len(
        user_skills
    )


def _calculate_final_score(
    text_similarity: float,
    skill_coverage: float,
    riasec_similarity: float,
    has_riasec_profile: bool,
) -> float:
    """
    Calculate the final hybrid recommendation score.

    When no RIASEC profile is provided, the score uses:
        70% TF-IDF similarity
        30% skill coverage

    When a RIASEC profile is provided:
        55% TF-IDF similarity
        25% skill coverage
        20% RIASEC similarity

    This keeps the core TF-IDF engine dominant while allowing
    the structured O*NET RIASEC profile to improve personalization.
    """
    if has_riasec_profile:
        score = (
            0.55 * text_similarity
            + 0.25 * skill_coverage
            + 0.20 * riasec_similarity
        )
    else:
        score = (
            0.70 * text_similarity
            + 0.30 * skill_coverage
        )

    return float(
        np.clip(score, 0.0, 1.0)
    )


# ---------------------------------------------------------------------------
# Main recommendation function
# ---------------------------------------------------------------------------

def match_careers(
    user_skills: Sequence[str],
    top_k: int = 10,
    preferred_industry: Optional[str] = None,
    user_riasec: Optional[Dict[str, float]] = None,
) -> List[Dict[str, Any]]:
    """
    Recommend careers based on user skills.

    Parameters
    ----------
    user_skills:
        Skills supplied by the user.

    top_k:
        Maximum number of recommendations.

    preferred_industry:
        Optional text filter.

    user_riasec:
        Optional RIASEC profile containing the six dimensions.

    Returns
    -------
    List[dict]
        Ranked career recommendations.

    Each result contains:
        - onet_soc_code
        - job_title
        - description
        - match_percentage
        - matched_skills
        - missing_skills
        - riasec_similarity
    """
    # ---------------------------------------------------------------
    # Validate inputs
    # ---------------------------------------------------------------

    skills = normalize_skills(
        user_skills
    )

    if not skills:
        raise ValueError(
            "At least one user skill is required."
        )

    if top_k < 1:
        raise ValueError(
            "top_k must be at least 1."
        )

    # Prevent unnecessarily large requests.
    top_k = min(
        int(top_k),
        len(occupation_order),
    )

    # ---------------------------------------------------------------
    # Build query
    # ---------------------------------------------------------------

    query_text = _build_user_search_text(
        skills
    )

    query_vector = vectorizer.transform(
        [query_text]
    )

    # ---------------------------------------------------------------
    # Calculate TF-IDF similarity
    # ---------------------------------------------------------------

    similarities = cosine_similarity(
        query_vector,
        occupation_matrix,
    )[0]

    # ---------------------------------------------------------------
    # Candidate ranking
    # ---------------------------------------------------------------

    candidate_indices = np.argsort(
        similarities
    )[::-1]

    results: List[Dict[str, Any]] = []

    for index in candidate_indices:

        if len(results) >= top_k:
            break

        soc_code = occupation_order[index]

        occupation = occupations.get(
            soc_code
        )

        if not occupation:
            continue

        # -----------------------------------------------------------
        # Industry filter
        # -----------------------------------------------------------

        if not _matches_industry(
            occupation,
            preferred_industry,
        ):
            continue

        # -----------------------------------------------------------
        # TF-IDF score
        # -----------------------------------------------------------

        text_similarity = float(
            np.clip(
                similarities[index],
                0.0,
                1.0,
            )
        )

        # -----------------------------------------------------------
        # Occupation skills
        # -----------------------------------------------------------

        occupation_skills = (
            _occupation_skill_names(
                occupation
            )
        )

        matched_skills, missing_skills = (
            _skill_matches(
                skills,
                occupation_skills,
            )
        )

        skill_coverage = (
            _calculate_skill_coverage(
                matched_skills,
                skills,
            )
        )

        # -----------------------------------------------------------
        # RIASEC similarity
        # -----------------------------------------------------------

        riasec_similarity = (
            _riasec_similarity(
                user_riasec,
                occupation,
            )
        )

        has_riasec_profile = (
            user_riasec is not None
        )

        # -----------------------------------------------------------
        # Final hybrid score
        # -----------------------------------------------------------

        final_score = _calculate_final_score(
            text_similarity=text_similarity,
            skill_coverage=skill_coverage,
            riasec_similarity=riasec_similarity,
            has_riasec_profile=has_riasec_profile,
        )

        results.append(
            {
                "onet_soc_code": soc_code,
                "job_title": occupation.get(
                    "title",
                    "",
                ),
                "description": occupation.get(
                    "description",
                    "",
                ),
                "match_percentage": round(
                    final_score * 100,
                    2,
                ),
                "matched_skills": matched_skills,
                "missing_skills": missing_skills,
                "text_similarity": round(
                    text_similarity,
                    4,
                ),
                "skill_coverage": round(
                    skill_coverage,
                    4,
                ),
                "riasec_similarity": round(
                    riasec_similarity,
                    4,
                ),
                "riasec": occupation.get(
                    "riasec",
                    {},
                ),
                "hot_technologies": occupation.get(
                    "hot_technologies",
                    [],
                ),
                "in_demand_software": occupation.get(
                    "in_demand_software",
                    [],
                ),
            }
        )

    # ---------------------------------------------------------------
    # Re-sort using final hybrid score
    # ---------------------------------------------------------------

    results.sort(
        key=lambda item: item[
            "match_percentage"
        ],
        reverse=True,
    )

    return results


# ---------------------------------------------------------------------------
# Convenience function
# ---------------------------------------------------------------------------

def get_career_recommendations(
    user_skills: Sequence[str],
    top_k: int = 10,
    preferred_industry: Optional[str] = None,
    user_riasec: Optional[Dict[str, float]] = None,
) -> List[Dict[str, Any]]:
    """
    Public wrapper around match_careers().

    This function provides a clean interface for the future
    FastAPI recommendation endpoint.
    """
    return match_careers(
        user_skills=user_skills,
        top_k=top_k,
        preferred_industry=preferred_industry,
        user_riasec=user_riasec,
    )


# ---------------------------------------------------------------------------
# Simple manual test
# ---------------------------------------------------------------------------

if __name__ == "__main__":

    sample_skills = [
        "Python",
        "SQL",
        "Machine Learning",
        "Statistics",
        "Problem Solving",
    ]

    recommendations = match_careers(
        user_skills=sample_skills,
        top_k=5,
    )

    print()
    print("=" * 70)
    print("CAREER RECOMMENDATIONS")
    print("=" * 70)

    for position, recommendation in enumerate(
        recommendations,
        start=1,
    ):

        print()
        print(
            f"{position}. "
            f"{recommendation['job_title']}"
        )

        print(
            f"   Match: "
            f"{recommendation['match_percentage']}%"
        )

        print(
            f"   SOC: "
            f"{recommendation['onet_soc_code']}"
        )

        print(
            f"   Matched skills: "
            f"{', '.join(recommendation['matched_skills'])}"
        )

        print(
            f"   Missing skills: "
            f"{', '.join(recommendation['missing_skills'])}"
        )

        print(
            f"   TF-IDF similarity: "
            f"{recommendation['text_similarity']}"
        )

        print(
            f"   Skill coverage: "
            f"{recommendation['skill_coverage']}"
        )

    print()