from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import List

import joblib
from sklearn.feature_extraction.text import TfidfVectorizer


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"
ARTIFACTS_DIR = PROJECT_ROOT / "data" / "artifacts"

INPUT_FILE = PROCESSED_DATA_DIR / "occupation_profiles.json"

TFIDF_OUTPUT = ARTIFACTS_DIR / "tfidf_vectorizer.pkl"
MATRIX_OUTPUT = ARTIFACTS_DIR / "occupation_matrix.pkl"
METADATA_OUTPUT = ARTIFACTS_DIR / "occupation_metadata.json"


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Configuration for TF-IDF
# ---------------------------------------------------------------------------

TFIDF_CONFIG = {
    "lowercase": True,
    "strip_accents": "unicode",
    "ngram_range": (1, 2),
    "min_df": 2,
    "max_df": 0.95,
    "sublinear_tf": True,
}


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_processed_data() -> dict:
    """
    Load the occupation profiles generated by preprocess.py.
    """
    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            f"Processed dataset not found: {INPUT_FILE}\n"
            "Run preprocess.py first."
        )

    logger.info(
        "Loading processed dataset: %s",
        INPUT_FILE,
    )

    with open(
        INPUT_FILE,
        "r",
        encoding="utf-8",
    ) as file:
        data = json.load(file)

    if "occupations" not in data:
        raise ValueError(
            "Processed dataset does not contain "
            "'occupations'."
        )

    occupations = data["occupations"]

    if not occupations:
        raise ValueError(
            "Processed dataset contains no occupations."
        )

    logger.info(
        "Loaded %d occupations",
        len(occupations),
    )

    return data


# ---------------------------------------------------------------------------
# Prepare training documents
# ---------------------------------------------------------------------------

def prepare_training_data(
    data: dict,
) -> tuple[List[str], List[str]]:
    """
    Prepare occupation documents for TF-IDF.

    Returns:
        documents:
            Searchable text for each occupation.

        soc_codes:
            O*NET-SOC code corresponding to each document.

    The order of both lists is identical and is therefore also
    the row order of the occupation matrix.
    """
    occupations = data["occupations"]

    documents: List[str] = []
    soc_codes: List[str] = []

    for soc_code, profile in occupations.items():

        search_text = profile.get(
            "search_text",
            "",
        )

        if not isinstance(search_text, str):
            search_text = str(search_text)

        search_text = search_text.strip()

        if not search_text:
            logger.warning(
                "Skipping %s because search_text is empty",
                soc_code,
            )
            continue

        documents.append(search_text)
        soc_codes.append(soc_code)

    if not documents:
        raise ValueError(
            "No valid occupation documents found."
        )

    logger.info(
        "Prepared %d occupation documents",
        len(documents),
    )

    return documents, soc_codes


# ---------------------------------------------------------------------------
# Train TF-IDF
# ---------------------------------------------------------------------------

def train_tfidf(
    documents: List[str],
) -> tuple[TfidfVectorizer, object]:
    """
    Fit the TF-IDF vectorizer and transform occupation documents.
    """
    logger.info(
        "Training TF-IDF vectorizer..."
    )

    vectorizer = TfidfVectorizer(
        **TFIDF_CONFIG
    )

    occupation_matrix = vectorizer.fit_transform(
        documents
    )

    logger.info(
        "TF-IDF training completed"
    )

    logger.info(
        "Documents: %d",
        occupation_matrix.shape[0],
    )

    logger.info(
        "Vocabulary size: %d",
        occupation_matrix.shape[1],
    )

    logger.info(
        "Matrix shape: %s",
        occupation_matrix.shape,
    )

    return vectorizer, occupation_matrix


# ---------------------------------------------------------------------------
# Build occupation metadata
# ---------------------------------------------------------------------------

def build_metadata(
    data: dict,
    soc_codes: List[str],
) -> dict:
    """
    Create metadata aligned with the rows of occupation_matrix.pkl.

    The row index in the matrix corresponds exactly to the index
    in occupation_order.
    """
    occupations = data["occupations"]

    metadata = {
        "version": "1.0",
        "source": data.get(
            "metadata",
            {},
        ).get(
            "source",
            "O*NET",
        ),
        "occupation_count": len(soc_codes),
        "occupation_order": soc_codes,
        "occupations": {},
    }

    for soc_code in soc_codes:

        profile = occupations[soc_code]

        metadata["occupations"][soc_code] = {
            "onet_soc_code": profile.get(
                "onet_soc_code",
                soc_code,
            ),
            "title": profile.get(
                "title",
                "",
            ),
            "description": profile.get(
                "description",
                "",
            ),
            "knowledge": profile.get(
                "knowledge",
                [],
            ),
            "abilities": profile.get(
                "abilities",
                [],
            ),
            "transferable_skills": profile.get(
                "transferable_skills",
                [],
            ),
            "essential_skills": profile.get(
                "essential_skills",
                [],
            ),
            "software_skills": profile.get(
                "software_skills",
                [],
            ),
            "hot_technologies": profile.get(
                "hot_technologies",
                [],
            ),
            "in_demand_software": profile.get(
                "in_demand_software",
                [],
            ),
            "specific_interests": profile.get(
                "specific_interests",
                [],
            ),
            "riasec": profile.get(
                "riasec",
                {},
            ),
        }

    return metadata


# ---------------------------------------------------------------------------
# Save artifacts
# ---------------------------------------------------------------------------

def save_artifacts(
    vectorizer: TfidfVectorizer,
    occupation_matrix,
    metadata: dict,
) -> None:
    """
    Save all Phase 1 ML artifacts.
    """
    ARTIFACTS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    logger.info(
        "Saving TF-IDF vectorizer..."
    )

    joblib.dump(
        vectorizer,
        TFIDF_OUTPUT,
    )

    logger.info(
        "Saved: %s",
        TFIDF_OUTPUT,
    )

    logger.info(
        "Saving occupation matrix..."
    )

    joblib.dump(
        occupation_matrix,
        MATRIX_OUTPUT,
    )

    logger.info(
        "Saved: %s",
        MATRIX_OUTPUT,
    )

    logger.info(
        "Saving occupation metadata..."
    )

    with open(
        METADATA_OUTPUT,
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            metadata,
            file,
            ensure_ascii=False,
            indent=2,
        )

    logger.info(
        "Saved: %s",
        METADATA_OUTPUT,
    )


# ---------------------------------------------------------------------------
# Training pipeline
# ---------------------------------------------------------------------------

def train() -> None:
    """
    Execute the complete Phase 1 training pipeline.
    """
    logger.info(
        "=========================================="
    )

    logger.info(
        "Starting Phase 1 ML training"
    )

    logger.info(
        "=========================================="
    )

    # 1. Load processed data
    data = load_processed_data()

    # 2. Prepare documents
    documents, soc_codes = prepare_training_data(
        data
    )

    # 3. Train TF-IDF
    vectorizer, occupation_matrix = train_tfidf(
        documents
    )

    # 4. Build metadata
    metadata = build_metadata(
        data,
        soc_codes,
    )

    # 5. Save artifacts
    save_artifacts(
        vectorizer,
        occupation_matrix,
        metadata,
    )

    logger.info(
        "=========================================="
    )

    logger.info(
        "Phase 1 ML training completed successfully"
    )

    logger.info(
        "=========================================="
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    try:
        train()

    except Exception as exc:
        logger.exception(
            "Training failed: %s",
            exc,
        )
        raise